before_script:
  - echo "deb httpredir.debian.org/debian jessie-backports main contrib non-free" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install -y virtualbox virtualbox-dkms vagrant
  - vagrant up

job:
  script:
    - vagrant ssh -c "cd /vagrant && vendor/bin/phpunit tests"
