before_script:
  - sh provision.sh
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
  - java -jar selenium-server-standalone-2.53.0.jar &

job:
  script:
    - vendor/bin/phpunit tests
